
Bayesian Identification of Gene Regulatory Networks

* Intro
  This document is a guide for the code in this directoriy which serves as the basis of my
Master's Thesis. All code was made during 2017 October to 2018 June, based on the VanillaID
system identification toolbox.

* Demo
For a stand-alone demo run demo.m. Note that this demo just runs the algorithm for 1
realisations and for different signal to noise ratios. This can still take couple of minutes


* Useful things to know
** Hill functions are too simple for my application. Can I use something more complicated?

Yes for identification, but not for generation, however it only needs a little bit of tweaking.

The abstraction file /interpretationGraph/ serves exactly this purpose. 

#+BEGIN_SRC matlab
interpret = interpretationGraph(1);
interpret = interpret.addBasisFunction(@(x) (x+3)^5);
#+END_SRC

This way you can add any kind of dictionary functions which will be evaluated for
all measured gene expressions that you supplied to the algorithm.

However, it is important that your function can only depend on *one gene*. Sadly, this
means that there is currently no way to extend to higher-order reactions. 
** I constructed a gene regulatory networks using /geneGraph/. I want to make sure that I simulate the right thing.

The function /geneGraph.showGraph/ will show a MATLAB figure with the gene regulatory network.
There is a preliminary imlementation /geneGraph.printGraph/ which let's you LaTeX TikZ graphs,
but it is not guaranteed to work. (edges often overlay on each other)

* File list
** Main folder

- changelog.txt :: I made a log on the changes in certain commits. It contains some information on what might be missing from the code, but it is not really helpful in my opinion.
- config.m :: A config file which adds the directories. All simulation runs are supposed to be run from the main folder.
- configserver.m :: A config file but for the server. The only difference is that it adds the CVX toolbox, because I found no other way to add the toolbox permanently from the server command line.
- dictionaryVisualisation.m :: Code for the visualisation of the dictionaries I've used in my thesis.
- eachSNR.mat :: A MAT which has combination of multiple runs.
- fisherAnimation.m :: A file which creates a GIF from the contents of a load file
- linearComparison.m :: preliminary code performing the oracle estimator lower bound calculations
- MAPdata.mat :: contains the combination of data used with MAP uncertainty sampling
- myColorMap.mat :: MAT file containing a colormap
- oracleLinear.mat :: a result of the linearComparison.m file
- Randomdata.mat :: contains results for randomised sampling
- serverprogressCheck.m :: checks progress of files on server
- serverprogress.mat :: auxiliary file for serverprogressCheck.m
- signalCorruption.m :: code used to noise derivative series
- sparseanimation3.gif :: animation generated by fisherAnimation.m
- tac_reconstruction.m :: Contains the actual code for the Sparse Bayesian Learning algorithm
- testSNR.m ::
- totalSNR.mat :: Another combination file with the Fisher Information metric
- trialRun.mat ::

** checkpoints 
A directory containing checkpoints for the simulations made on the server

** errorModel 

- experimentMerge.m :: merge the experiments from multiple mat files
- experimentMergeRandom.m :: exact replica of the first one with different filenames, just for convenience reasons
- graphFactoryReport2.m :: file comparing random and MAP uncertainty sampling
- graphFactoryReport.m :: file producing all the graphs in the thesis
- oracleCalculator.m :: A little snippet for calculating the oracle estimator
- results :: This folder has all the figures which are in the thesis

** simulationFiles

- fisherBasesParallel.m :: Varying the amount of bases to give indication how well the algorithm performs
subset selection - parallalised
- fisherNoiseless.m :: a single noiseless simulation of the repressilator with Fisher information adding
- fisherRepParallel.m :: Fisher Information Based sampling PARALLEL
- fisherRepParallelPinv.m :: uses the pseudoInverse ordering
- fisherRepressilator.m :: Fisher Information Based sampling
- gammaRepParallel.m :: Gamma repressilator, which uses parallelised adaptive sampling
- maxFisherDictionaryBatch.m :: lambda normalised Fisher code
- maxFisherDictionary.m :: 
- maxGammaDictionary.m :: performs adaptive MAP based uncertainty sampoling
- maxRegDetDictionaryBatch.m :: performs MAP based uncertainty sampling
- maxTraceFisherDictionaryBatch.m :: used to pinv
- randomSamplingRepressilator.m :: samples randomly

** simulationLibrary

- demo :: demo folder containing some repressilator toy code 
- geneGraph.m :: - abstraction file for gene regulatory networks 
- html :: 
- identificationTest.m :: testing whether identification works or not but this is old code so not guaranteed to work 
- interpretationGraph.m :: abstraction for identification
- rungeKuttaExample.m :: 
- rungeKuttaTest.m :: 
- simGraph.m :: lower lewel abstraction for gene regulatory networks 
- testGeneGraph.m :: test file for gene graph 
- testSimGraph.m :: test file for simulation graph
- twoGeneNetworkGenerator.m :: 

** utilities 

- colorMapStore2.mat :: A version of color map for dictionary visualisation
- colorMapStore3.mat :: A version of color map for dictionary visualisation
- colormapStore.mat :: A version of color map for dictionary visualisation
- eachSNRgf2.mat :: No idea
- figureFormatter.m :: My figure formatter code to makes figures look nicer



     




